%According to the paper, we initial the program with 50 persons and compare problog and PFL with increasing attributes for each person.

attr(weather).
attr(timeofWorkshop).
attr(topic).
attr(instructor).
attr(durationofWorkshop).
attr(topic-CWL).
attr(topic-AI).
attr(topic-ML).
attr(topic-BigData).

person(proffodor).
person(rakshith).
person(dinesh).
person(prashanth).
person(dyuman).
person(sravan).
person(venkat).
person(laxmi).
person(shalini).
person(kishan).
person(nikhil).
person(sreeram).
person(charan).
person(madan).
person(jayadev).
person(naresh).
person(mohan).
person(gandhi).
person(sharan).
person(siddarth).
person(srinivas).
person(anudeep).
person(sravani).
person(anuja).
person(sree).
person(sujan).
person(vinod).
person(rahul).
person(sowmyakanth).
person(ysr).
person(tdp).
person(cbn).
person(jagan).
person(mahesh).
person(busa).
person(pawan).
person(ramcharan).
person(alluarjun).
person(sharukh).
person(amir).
person(vijay).
person(ajit).
person(vipula).
person(reshma).
person(poojitha).
person(asmitha).
person(arun).
person(sandeep).
person(undavalli).
person(rajkumar).
